apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rsweb1

spec:
  replicas: 4
  selector:
    matchLabels:
      dc: IN 
      app: webserver
      env: dev
    matchExpressions:
     - { key: dc , operator: In , values: [IN , US ] }
     - { key: env , operator: In , values: [ dev ] }
     - { key: app , operator: In , values: [ webserver ] }
  template:
    metadata:
     name: mypod1
     labels:
       env: dev
       dc: IN
       app: webserver
    spec:
     containers: 
       - name: "mycon1"
         image: "vimal13/apache-webserver-php"
         env:
          - name: x
            value: something
          - name: x
            value: "10"